### ISSUE TITLE
Melhorias na tela de login

### ISSUE THREAD

**Issue by carolinesalib** [carolinesalib/tweet-stalker#11]
Melhorar tela para que atenda as necessidades abaixo:

- [x] Deve ser retirado os botões sign in e sign up;
- [x] Alterar descrição para algo como "Seja bem vindo ao TweetStalker" e "Desenvolvido by >nossos twitters<";
- [x] Atualizar a logo para a logo que foi definida ou uma logo temporária do twitter;
- [x] Adicionar botão para autentificação diretamente pelo twitter (botão já existente).

**Comment by carolinesalib** [comment]
Olá, quando clicar em "Sign in" ainda levará para outra página, pois acho que faz parte de padrão para trabalhar com a sessão depois, mas podemos conversar sobre isso.

Favor verificar alterações, @gabrielms.

**Comment by gabrielms** [comment]
Olá @carolinesalib.

Agora está ok, muito bom!
