### ISSUE TITLE
Criar pasta para API e mover app para nova pasta separada

### ISSUE THREAD

**Issue by gabrielms** [carolinesalib/tweet-stalker#13]
- [x] Criar nova API usando Rails API na pasta tweet-stalker-api;
- [x] Mover o projeto atual para a pasta tweet-stalker-app;

**Comment by gabrielms** [comment]
Olá @carolinesalib.

Feito, favor verificar.

**Comment by carolinesalib** [comment]
Olá, verificado!

**Comment by gabrielms** [comment]
Olá @carolinesalib.

Conforma conversamos atualizei para o RAILS 5, agora é um projeto puramente API.
